routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('home');
// });

Route::resource('product','ProductController');
//Route::resource('/category','CategoryController');

Route::get('/', 'PagesController@home');


Route::get('/shop', 'ShopController@index')->name('shop.index');
Route::get('/cart.index', 'CartController@index')->name('cart.index');
Route::post('/cart.store', 'CartController@store')->name('cart.store');
Route::delete('/cart/{product}', 'CartController@destroy')->name('cart.destroy');
Route::post('/cart.switchToSaveForLater/{product}', 'CartController@switchToSaveForLater')->name('cart.switchToSaveForLater');

Route::delete('/saveForLater/{product}', 'SaveForLaterController@destroy')->name('saveForLater.destroy');
Route::post('/saveForLater.switchToCart/{product}', 'SaveForLaterController@switchToCart')->name('saveForLater.switchToCart');

Route::get('empty', function(){
    Cart::instance('saveForLater')->destroy();
});

Route::get('/product.create', 'ProductController@create');
Route::get('/product.show/{product}', 'ProductController@show');
Route::delete('/product.delete/{id}', 'ProductController@destroy');


Route::get('/cart', 'ShopController@show');
Route::get('/order.index', 'OrderController@index')->name('order.index')->middleware('auth');
Route::post('/order', array('as' => 'store', 'uses' => 'OrderController@store'));
Route::get('/order.show', 'OrderController@show')->name('order.show');
Route::get('/order.view/{product}', 'OrderController@view');

Route::get('/guestOrder.index', 'OrderController@index')->name('guestOrder.index');


Route::get('/admin/category.create', 'CategoryController@create');


Route::prefix('admin')->group(function() {
    Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
    Route::get('/dashboard', 'AdminController@index')->name('admin.dashboard');
});

Auth::routes();

Route::get('/dashboard', 'DashboardController@index');
Route::post('/product', 'ProductController@store');
Route::post('/category', 'CategoryController@store');
Route::get('/category.create', 'CategoryController@create');

Route::get('/product/{product}/edit', 'ProductController@edit');
Route::put('product/{product}', 'ProductController@update');

Route::middleware('auth')->group(function(){
    Route::get('/my-profile', 'UsersController@edit')->name('users.edit');
    Route::post('/my-profile', 'UsersController@update')->name('users.update');

});

resources/views/admin/dashboard.blade.php
@extends('layouts.app')

@section('content')
<div class="wrap" style="width: 100%;">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header ">Admin Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif
					 <div class="sidebar">
						
					</div>
                   <button class="btn btn-success"><a class="text-white" href="/product.create">Add Product</a></button>
                   <button class="btn btn-success"><a class="text-white" href="/category.create">Add category</a></button>
                   <button class="btn btn-success">Add Best Product</button>
                   <button class="btn btn-success">Settings</button>
                   <button class="btn btn-success"><a class="text-white" href="/order.show">Orders</a></button>
                    

                </div>

                <div class="wrap">
                    <table class="table table-striped">
                        <thead class="thead-dark">
                          <tr>
                            <th scope="col">Image</th>
                            <th scope="col">Product name</th>
                            <th scope="col">Design</th>
                            <th scope="col">Color</th>
                            <th scope="col">Description</th>
                            <th scope="col">Price</th>
                            <th scope="col">Discount</th>
                            <th scope="col">Best seller</th>
                            <th scope="col">Update</th>
                            <th scope="col">Delete</th>
                          </tr>
                        </thead>
                        <tbody>
                            @foreach ($products as $product)                  
                                <tr>
                                <th scope="row"><img src="/storage/Product_images/{{$product->image}}" style="width: 60px; height: 60px;" alt=""></th>
                                    <td>{{$product->name}}</td>
                                    <td>{{$product->design}}</td>
                                    <td>{{$product->color}}</td>
                                    <td>{{$product->description}}</td>
                                    <td>{{$product->price}} din</td>
                                    <td>{{$product->discount}} %</td>
                                    <td> <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios2" value="option2"></td>
                                    <td><button class="btn btn-warning" ><a style="color:white;" href="/product/{{$product->id}}/edit">Edit</a></button></td>
                                    <td>
                                        <form action="{{route('product.destroy', $product->id)}}" method="POST">
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-danger">Delete</button>
                                        </form>
                                    </td>
                                </tr>     
                            @endforeach
                        </tbody>
                      </table>
                </div>   
                <div class="alert ">
                    @if(session()->has('message'))
                        <div class="alert alert-success">
                            {{ session()->get('message') }}
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>




@endsection